networks:
  local:
    name: internal
    driver: bridge


services:
  express-sample:
    container_name: express-server
    #restart: unless-stopped
    image: express-server:1
    networks:
      - local # refers to the network defined above line 2, what its name, actualy, is 'internal'

  rtmp:
    container_name: rtmp-server
    image: rtmp-server:2
    networks:
      - local # refers to the network defined above line 2, what its name, actualy, is 'internal'


  nginx:
    container_name: reverse-proxy-server
    #restart: unless-stopped
    image: chaimfn/nginx:1.26.0.netfree
    networks:
      - local # refers to the network defined above line 2, what its name, actualy, is 'internal'
    volumes:
      - $PWD/reverse-proxy-server/docker.local.crt:/etc/ssl/docker.local.crt
      - $PWD/reverse-proxy-server/docker.local.key:/etc/ssl/docker.local.key
      - $PWD/reverse-proxy-server/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/reverse-proxy-server/express-server.conf:/etc/nginx/conf.d/express-server.conf
    ports:
      - "8880:80"
      - "4443:443"
      - "1935:1935"


